### ISSUE TITLE
学习libcurl

### ISSUE THREAD

**Issue by xiaoliuzi** [xiaoliuzi/netlib_demo#9]
用c写一个使用libcurl访问nginx的hello world程序

**Comment by xiaoliuzi** [comment]
完成GET/POST提交请求程序。
完成获取html网页程序。

另，暂时还没有研究Echo Server怎么写，http协议，基本可以使用。
请问是否可以暂缓http类型的Echo Server的书写.
@starwing

**Comment by starwing** [comment]
可以的～这个以后再说

**Comment by xiaoliuzi** [comment]
哦、好的。那我直接勾上了。
